import { action } from "./_generated/server";
import { api } from "./_generated/api";
import { v } from "convex/values";

function getOrgIdFromApiKey(apiKey: string): string | null {
  if (!apiKey.startsWith("apk_")) return null;
  const parts = apiKey.substring(4).split(":");
  if (parts.length === 0) return null;
  try {
    return Buffer.from(parts[0], "base64").toString("utf-8");
  } catch (e) {
    return null;
  }
}

export const generateDeckFromUrl = action({
  args: {
    url: v.string(),
    taskId: v.string(),
  },
  handler: async (ctx, args) => {
    const { url, taskId } = args;

    // Get API Keys from environment
    const contextDevApiKey = process.env.CONTEXT_DEV_API_KEY || "ctxt_secret_dummy";
    const devinApiKey = process.env.DEVIN_API_KEY || "cog_dummy";

    try {
      // Check if we should trigger Devin
      let devinTriggered = false;
      if (devinApiKey && devinApiKey.startsWith("apk_")) {
        const orgId = getOrgIdFromApiKey(devinApiKey);
        if (orgId) {
          console.log(`Triggering Devin session for task ${taskId} (Org ID: ${orgId})...`);
          try {
            const prompt = `You are a helper developer agent for the Langer app.
Please do the following task:
1. Crawl/Scrape the webpage at: ${url}
2. Extract 3 main vocabulary words from this page. For each word, find:
   - The word itself
   - Phonetic pronunciation
   - Concise definition/meaning
   - A contextual example sentence from the page or related to the page content
3. Write this generated vocabulary deck back to our Convex database by running commands in the workspace.
   Specifically, you can execute these mutations directly from the command line using npx convex run:
   - tasks:saveGeneratedDeck '{"deckId": "deck-${taskId}", "name": "Vocab from URL", "description": "Generated by Devin from ${url}", "category": "Brainstorm"}'
   - tasks:saveGeneratedCard '{"deckId": "deck-${taskId}", "word": "word1", "phonetic": "...", "meaning": "...", "example": "...", "imageUrl": "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?auto=format&fit=crop&w=300&q=80", "audioUrl": "https://actions.google.com/sounds/v1/alarms/digital_watch_alarm_long.ogg"}'
   - tasks:saveGeneratedCard '{"deckId": "deck-${taskId}", "word": "word2", "phonetic": "...", "meaning": "...", "example": "...", "imageUrl": "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?auto=format&fit=crop&w=300&q=80", "audioUrl": "https://actions.google.com/sounds/v1/alarms/digital_watch_alarm_long.ogg"}'
   - tasks:saveGeneratedCard '{"deckId": "deck-${taskId}", "word": "word3", "phonetic": "...", "meaning": "...", "example": "...", "imageUrl": "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?auto=format&fit=crop&w=300&q=80", "audioUrl": "https://actions.google.com/sounds/v1/alarms/digital_watch_alarm_long.ogg"}'
   - tasks:finishTask '{"taskId": "${taskId}", "deckId": "deck-${taskId}"}'
4. Ensure the task status is marked as complete by calling finishTask.
This project is already configured with Convex in this workspace. You can run npx convex dev --once to make sure functions are up to date, and then npx convex run to execute the mutations.`;

            await ctx.runMutation(api.tasks.updateState, {
              taskId,
              status: "Initializing Devin session...",
              markdown: null,
              sessionId: null,
            });

            const devinRes = await fetch(`https://api.devin.ai/v3/organizations/${orgId}/sessions`, {
              method: "POST",
              headers: {
                "Authorization": `Bearer ${devinApiKey}`,
                "Content-Type": "application/json",
              },
              body: JSON.stringify({
                prompt: prompt,
              }),
            });

            if (devinRes.ok) {
              const devinData: any = await devinRes.json();
              const sessionId = devinData.id || devinData.session_id;
              if (sessionId) {
                console.log(`Devin session successfully created: ${sessionId}`);
                await ctx.runMutation(api.tasks.updateState, {
                  taskId,
                  status: "Devin session active. Waiting for Devin to compile the deck...",
                  markdown: `Prompt: Extract words from ${url}`,
                  sessionId: sessionId,
                });
                devinTriggered = true;
              }
            } else {
              const errorText = await devinRes.text();
              console.error(`Failed to trigger Devin session: ${devinRes.status} - ${errorText}`);
            }
          } catch (err) {
            console.error("Error calling Devin API:", err);
          }
        }
      }

      if (devinTriggered) {
        return;
      }

      // 1. Attempt structured extraction via Context.dev
      console.log(`Extracting vocabulary from ${url} via Context.dev...`);
      await ctx.runMutation(api.tasks.updateState, {
        taskId,
        status: "Extracting vocabulary using AI...",
        markdown: null,
        sessionId: null,
      });

      let deckName = `Vocab from URL`;
      let deckDescription = `Vocabulary generated by AI from ${url}`;
      let words: Array<{ word: string; phonetic: string; meaning: string; example: string }> = [];

      let hasExtracted = false;

      if (contextDevApiKey && contextDevApiKey !== "ctxt_secret_dummy") {
        try {
          const extractRes = await fetch("https://api.context.dev/v1/web/extract", {
            method: "POST",
            headers: {
              "Authorization": `Bearer ${contextDevApiKey}`,
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              url,
              schema: {
                type: "object",
                properties: {
                  deckName: { type: "string" },
                  deckDescription: { type: "string" },
                  words: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        word: { type: "string" },
                        phonetic: { type: "string" },
                        meaning: { type: "string" },
                        example: { type: "string" }
                      },
                      required: ["word", "phonetic", "meaning", "example"]
                    }
                  }
                },
                required: ["deckName", "deckDescription", "words"]
              }
            }),
          });

          if (extractRes.ok) {
            const extractData: any = await extractRes.json();
            const extraction = extractData.data || extractData;
            if (extraction && extraction.words && extraction.words.length > 0) {
              deckName = extraction.deckName || deckName;
              deckDescription = extraction.deckDescription || deckDescription;
              words = extraction.words;
              hasExtracted = true;
              console.log("Successfully extracted via Context.dev web/extract API!");
            }
          }
        } catch (err) {
          console.error("Context.dev extraction error, falling back to scrape...", err);
        }
      }

      // 2. Fallback to scraping and dynamic parsing if extract was not successful
      if (!hasExtracted) {
        console.log(`Scraping webpage ${url} via Context.dev...`);
        await ctx.runMutation(api.tasks.updateState, {
          taskId,
          status: "Scraping webpage (via Context.dev)...",
          markdown: null,
          sessionId: null,
        });

        let markdown = "No content found";
        let title = "AI Generated Deck";

        try {
          const scrapeRes = await fetch(`https://api.context.dev/v1/web/scrape/markdown?url=${encodeURIComponent(url)}`, {
            method: "GET",
            headers: {
              "Authorization": `Bearer ${contextDevApiKey}`,
            },
          });

          if (scrapeRes.ok) {
            const scrapeData: any = await scrapeRes.json();
            markdown = scrapeData.markdown || markdown;
            title = scrapeData.title || title;
          }
        } catch (err) {
          console.error("Scrape error, using title/URL templates...", err);
          title = url.replace(/https?:\/\/(www\.)?/, "").split("/")[0] || "AI Web Deck";
        }

        deckName = `Vocab: ${title.substring(0, 25)}`;
        deckDescription = `Vocabulary generated dynamically from ${url}`;

        // Extract 3 words dynamically from the markdown text
        // Clean words: filter for length > 6 and alphabetical characters only
        const textParts = markdown
          .replace(/[#*`_\[\]()\-:.,!?\n]/g, " ")
          .split(/\s+/)
          .filter(w => w.length > 6 && /^[a-zA-Z]+$/.test(w));
        
        const uniqueWords = Array.from(new Set(textParts))
          .map(w => w.toLowerCase())
          .filter(w => !["language", "programming", "software", "development", "context", "website", "content"].includes(w))
          .slice(0, 3);

        if (uniqueWords.length >= 3) {
          words = uniqueWords.map(w => ({
            word: w,
            phonetic: `/ ${w} /`,
            meaning: `Vocabulary term extracted dynamically from the webpage context of ${title.substring(0, 20)}.`,
            example: `This article discusses concepts related to ${w} as part of its core topic.`,
          }));
        } else {
          // Absolute fallback if not enough words found: use URL and timestamp-based dynamic template
          const timestamp = Date.now().toString().slice(-4);
          words = [
            {
              word: `dynamic_${timestamp}`,
              phonetic: `/ daɪˈnæmɪk /`,
              meaning: "Characterized by constant change, activity, or progress.",
              example: `The content on ${url} is dynamic and changes over time.`,
            },
            {
              word: `context_${timestamp}`,
              phonetic: `/ ˈkɒntekst /`,
              meaning: "The circumstances that form the setting for an event, statement, or idea.",
              example: `Reading terms in context facilitates quicker semantic retention.`,
            },
            {
              word: `extract_${timestamp}`,
              phonetic: `/ ɪkˈstrækt /`,
              meaning: "Remove or take out, especially by effort or force.",
              example: `We successfully extract distinct vocabularies from web articles.`,
            }
          ];
        }
      }

      // 3. For the demo, wait 3 seconds to simulate progress in real-time UI
      await new Promise((resolve) => setTimeout(resolve, 3000));

      const deckId = `deck-${Date.now()}`;
      
      // Save the generated deck
      await ctx.runMutation(api.tasks.saveGeneratedDeck, {
        deckId,
        name: deckName,
        description: deckDescription,
        category: "Brainstorm",
      });

      // Save the generated cards
      for (let i = 0; i < words.length; i++) {
        const w = words[i];
        await ctx.runMutation(api.tasks.saveGeneratedCard, {
          deckId,
          word: w.word,
          phonetic: w.phonetic,
          meaning: w.meaning,
          example: w.example,
          imageUrl: `https://images.unsplash.com/photo-1546410531-bb4caa6b424d?auto=format&fit=crop&w=300&q=80`,
          audioUrl: `https://actions.google.com/sounds/v1/alarms/digital_watch_alarm_long.ogg`,
        });
      }

      // 4. Set status to finished and save the deck ID
      await ctx.runMutation(api.tasks.finishTask, {
        taskId,
        deckId,
      });

      console.log(`Web-to-Flashcard generator finished! Saved Deck ID ${deckId}`);
    } catch (e: any) {
      console.error(e);
      await ctx.runMutation(api.tasks.updateState, {
        taskId,
        status: `Error: ${e.message}`,
        markdown: null,
        sessionId: null,
      });
    }
  },
});
