import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // This will store our task state sync
  tasks: defineTable({
    taskId: v.string(),
    taskStatus: v.string(),
    extractedMarkdown: v.optional(v.string()),
    devinSessionId: v.optional(v.string()),
    devinLogs: v.array(v.string()),
    generatedDeckId: v.optional(v.string()),
  }).index("by_taskId", ["taskId"]),

  // Decks generated by AI or synced
  decks: defineTable({
    id: v.string(),
    name: v.string(),
    description: v.string(),
    category: v.string(),
    dailyLimit: v.number(),
  }).index("by_langerId", ["id"]),

  // Flashcards generated by AI
  flashcards: defineTable({
    id: v.string(),
    deckId: v.string(),
    word: v.string(),
    phonetic: v.string(),
    meaning: v.string(),
    example: v.string(),
    imageUrl: v.string(),
    audioUrl: v.optional(v.string()),
  }).index("by_langerId", ["id"])
    .index("by_deckId", ["deckId"]),
});
